Display teams
Abbe-and-Gabbe/football-manager pull request #16
Opened 2023-02-12 13:46 UTC by GabrielAdward

2023-02-21 14:05 UTC, albinforsbergju requested changes

2023-02-21 14:05 UTC, albinforsbergju commented on football-manager/src/lib/Pages/DisplayTeams/DTNavbar.svelte
> +  </div>
No need for this, we already have a navbar for club.

2023-02-21 14:05 UTC, albinforsbergju commented on football-manager/src/lib/Pages/DisplayTeams/Teams.svelte
> +<DtNavbar {id} />
Use club navbar

2023-02-23 16:47 UTC, GabrielAdward commented on football-manager/src/lib/Pages/DisplayTeams/DisplayAllTeams.svelte
> +<section class="animate-fade-in flex-col mt-10">
Talked about it in school, will see how we set up the database and then change what needs to be changed.

2023-02-23 20:07 UTC, albinforsbergju requested changes
Fix!

2023-02-23 20:07 UTC, albinforsbergju commented on football-manager/src/App.svelte
> +
Route element not closed. App won't start.

2023-02-23 22:22 UTC, albinforsbergju approved these changes
LGTM!

2023-02-23 22:22 UTC, merged