FetxhDataCalendar
Abbe-and-Gabbe/football-manager pull request #46
Opened 2023-03-22 16:15 UTC by GabrielAdward

2023-03-23 11:34 UTC, GabrielAdward commented
@albinforsbergju activities route får inte fram data så har endast försökt fetcha games. Får undefined, skulle du kunna gå igenom min kod?

2023-03-23 11:49 UTC, albinforsbergju requested changes

2023-03-23 11:49 UTC, albinforsbergju commented on football-manager/src/lib/Pages/Club/ClubCalendar/ClubCalendar.svelte
> +      }
```suggestion
        games = data
        console.log(games)
```
Check postman, request only contains one array, not the a game object

2023-03-23 11:49 UTC, albinforsbergju commented on football-manager/src/lib/Pages/Club/ClubCalendar/ClubCalendar.svelte
The data is structured a little different than it was in your implementation, but should be easy to fix!

2023-03-23 11:51 UTC, albinforsbergju requested changes

2023-03-23 11:51 UTC, albinforsbergju commented on football-manager/src/lib/Pages/Club/ClubCalendar/ClubCalendar.svelte
> +    .then((res) => {
```suggestion
    const fetchGames = fetch(`http://localhost:8080/club/${id}/games`)
    
    fetchGames.then((res) => {
```

2023-03-23 11:52 UTC, albinforsbergju commented on football-manager/src/lib/Pages/Club/ClubCalendar/ClubCalendar.svelte
> +    .then((res) => {
Think it does not really matter, but since we have written it that way in the other files, we should do it here to.

2023-03-25 19:48 UTC, albinforsbergju approved these changes
LGTM!

2023-03-25 19:48 UTC, merged